server:
  port: 8889

spring:
  datasource:
    url: jdbc:mysql://42.193.142.13:3306/wiki?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Server2008!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
       map-underscore-to-camel-case: true #下划线转驼峰

# 打印所有的sql日志：sql, 参数, 结果
logging:
  level:
    com:
      backbook:
        wiki:
          mapper: trace